### ISSUE TITLE
Extension Outdated! 

### ISSUE THREAD

**Issue by devxbasit** [anerua/gnome-colorful-battery-indicator#1]
The extension is not working on Ubuntu 22.4 LTS (GNOME 42.0) 

![image](https://user-images.githubusercontent.com/24441401/165998009-987a3747-0bf1-4c96-9601-d0462efbd417.png)

**Comment by anerua** [comment]
Support added for GNOME 42

**Comment by devxbasit** [comment]
@anerua Kindly add support for GNOME **43**
