### ISSUE TITLE
Extension doesn't work parallelly with other extensions that tweak the battery percentage icon 

### ISSUE THREAD

**Issue by realKarthikNair** [anerua/gnome-colorful-battery-indicator#2]
eg this extension breaks when [this extension](https://extensions.gnome.org/extension/4862/bat_consumption_wattmeter/) is installed

**Comment by anerua** [comment]
Hi Karthik,

Please note that extensions that tweak the battery icon (including this extension) do so by creating a custom power indicator. This means any tweak already made on the power indicator is lost when the new custom power indicator is created by another extension. Hence, these types of extensions don't work together. 

Sorry for your experience.

**Comment by realKarthikNair** [comment]
@anerua got it. Thank you for the info.

The response is appreciated
