### ISSUE TITLE
Colors doesn't show on the lock screen

### ISSUE THREAD

**Issue by Biasio** [anerua/gnome-colorful-battery-indicator#3]
Hi, 
in gnome the extension is working fine, but on the lock screen the icon returns to the default design, after unlocking the screen the colors returns.
I don't know if this is related to gnome extensions or the extension itself...

**Comment by anerua** [comment]
Hi @Biasio,

One of the requirements of a standard gnome shell extension is to have it disabled on the lock screen. There are steps to get approval to circumvent this behavior. Definitely look into that.

Thanks for pointing it out.

**Comment by anerua** [comment]
Hi @Biasio,

This issue has been resolved. The extension works just fine now, even on the lock screen.

Thank you.
